GET http://localhost:8080/user/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2I2ZTY0YjlkNDUwYTg2NDY4NDI5ZTEiLCJ1c2VybmFtZSI6Im1hbmVlc2hAZ21haWwuY29tIiwiaWF0IjoxNzQwMDU5NDQ3LCJleHAiOjE3NDAwNjMwNDd9.54sJ-e4AEInhohJG4VtSC3pqe600AUMsWXj5m1VmJ1g