GET http://localhost:8080/common/getTime
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2I2ZTY0YjlkNDUwYTg2NDY4NDI5ZTEiLCJ1c2VybmFtZSI6Im1hbmVlc2hAZ21haWwuY29tIiwiaWF0IjoxNzQwMDQ4Mzg1LCJleHAiOjE3NDAwNTE5ODV9.bxxfdvoYJjjAMy6MOjTrvEUXdAmxVfTgjwxiKXkn0GY